name: Push Image to ECR

on:
  # Trigger the workflow on push, only for main branch.
  push:
    branches:
      - main
jobs:
  push_to_registry:
    name: Push Docker image to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build and push Docker image to ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com
          rev=$(git rev-parse --short HEAD)
          docker build . -t skallbankapi:$rev
          docker tag skallbankapi:$rev 244530008913.dkr.ecr.eu-west-1.amazonaws.com/maen030:$rev
          docker tag skallbankapi:$rev 244530008913.dkr.ecr.eu-west-1.amazonaws.com/maen030:latest
          docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/maen030:$rev
          docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/maen030:latest